<?php

namespace Drupal\dynamic_image_style;

use Drupal\Core\Cache\CacheBackendInterface;
use Drupal\Core\Extension\ModuleHandlerInterface;
use Drupal\Core\KeyValueStore\KeyValueFactoryInterface;
use Drupal\Core\KeyValueStore\KeyValueStoreInterface;
use Drupal\image\Entity\ImageStyle;
use Drupal\image\ImageStyleInterface;

/**
 * Helper for dynamic generation of image styles.
 *
 * @author Kodamera AB <info@kodamera.se>
 */
class DynamicImageStyleHelper {

  /**
   * The key value collection holding all valid settings strings.
   */
  const VALID_SETTINGS_COLLECTION = 'dynamic_image_style.valid_settings';

  /**
   * The cache ID used for valid settings before they moved to key value.
   */
  const LEGACY_VALID_SETTINGS_CID = 'dynamic_image_style:valid_settings';

  /**
   * The module handler service.
   */
  protected ModuleHandlerInterface $moduleHandler;

  /**
   * The default cache backend.
   */
  protected CacheBackendInterface $cache;

  /**
   * The key value store holding all valid settings strings.
   */
  protected KeyValueStoreInterface $validSettingsStore;

  /**
   * Valid settings strings already stored, loaded once per request.
   *
   * @var array<string, bool>|null
   */
  protected ?array $storedValidSettings = NULL;

  /**
   * Constructs the DynamicImageStyleHelper object.
   */
  public function __construct(ModuleHandlerInterface $module_handler, CacheBackendInterface $cache, KeyValueFactoryInterface $key_value_factory) {
    $this->moduleHandler = $module_handler;
    $this->cache = $cache;
    $this->validSettingsStore = $key_value_factory->get(self::VALID_SETTINGS_COLLECTION);
  }

  /**
   * Checks that a settings string only contains supported settings.
   *
   * Settings end up in the image style name and the derivative path, so this
   * rejects anything that is not a known setting, like path separators.
   *
   * @param string $settings_string
   *   The settings string, e.g. "16x9r_320w_2x".
   *
   * @return bool
   *   TRUE if the settings string is valid, else FALSE.
   */
  public static function isValidSettingsString(string $settings_string): bool {
    if ($settings_string === '') {
      return FALSE;
    }

    $keys = [];
    foreach (explode('_', $settings_string) as $part) {
      if (preg_match('/^[1-9]\d*[wh]$/', $part)) {
        $key = substr($part, -1);
      }
      elseif (preg_match('/^(0|[1-9]\d*)(\.\d+)?x$/', $part) && (float) $part > 0) {
        $key = 'x';
      }
      elseif (preg_match('/^((0|[1-9]\d*)(\.\d+)?)x((0|[1-9]\d*)(\.\d+)?)r$/', $part, $matches) && (float) $matches[1] > 0 && (float) $matches[4] > 0) {
        $key = 'r';
      }
      else {
        return FALSE;
      }

      // Each setting may only be given once.
      if (isset($keys[$key])) {
        return FALSE;
      }
      $keys[$key] = TRUE;
    }

    // An aspect ratio needs a width or a height to calculate from.
    if (isset($keys['r']) && !isset($keys['w']) && !isset($keys['h'])) {
      return FALSE;
    }

    return TRUE;
  }

  /**
   * Checks whether a settings string has been generated by a Twig filter.
   *
   * @param string $settings
   *   The settings string.
   *
   * @return bool
   *   TRUE if the settings string is allowed to be requested, else FALSE.
   */
  public function isAllowedSettings(string $settings): bool {
    if (!static::isValidSettingsString($settings)) {
      return FALSE;
    }

    if (isset($this->storedValidSettings[$settings]) || $this->validSettingsStore->has($settings)) {
      return TRUE;
    }

    // Accept settings stored by earlier versions of this module, so pages
    // rendered before an update keep working.
    $legacy = $this->cache->get(self::LEGACY_VALID_SETTINGS_CID);
    if ($legacy && in_array($settings, $legacy->data, TRUE)) {
      $this->addValidSettings($settings);
      return TRUE;
    }

    return FALSE;
  }

  /**
   * Returns all settings strings that have been generated by Twig filters.
   *
   * @return string[]
   *   The valid settings strings.
   */
  public function getValidSettings(): array {
    return array_keys($this->validSettingsStore->getAll());
  }

  /**
   * Creates an image style based on settings string.
   *
   * @param string $settings_string
   *   The string with image style settings.
   * @param bool $save
   *   True if the image style should be saved, else false.
   *
   * @return \Drupal\image\ImageStyleInterface
   *   The generated image style.
   *
   * @throws \Drupal\Core\Entity\EntityStorageException
   */
  public function createImageStyle(string $settings_string, bool $save = FALSE): ImageStyleInterface {
    // Generate the machine name based on settings string.
    $machine_name = 'dynamic_' . $settings_string;

    // Create image style.
    $image_style = ImageStyle::create([
      'name' => $machine_name,
      'label' => $machine_name,
    ]);

    $settings = $this->parseSettings($settings_string);

    $use_focal_point = $this->moduleHandler->moduleExists('focal_point');

    // Determine effect.
    if (array_key_exists('w', $settings) && array_key_exists('h', $settings)) {
      // Scale and crop.
      $image_style->addImageEffect([
        'id' => $use_focal_point ? 'focal_point_scale_and_crop' : 'image_scale_and_crop',
        'data' => [
          'width' => $settings['w'],
          'height' => $settings['h'],
          'anchor' => 'center-center',
          'weight' => 1,
        ],
      ]);
    }
    elseif (array_key_exists('w', $settings)) {
      // Scale with width.
      $image_style->addImageEffect([
        'id' => 'image_scale',
        'data' => [
          'width' => $settings['w'],
          'upscale' => TRUE,
          'weight' => 1,
        ],
      ]);
    }
    elseif (array_key_exists('h', $settings)) {
      // Scale with height.
      $image_style->addImageEffect([
        'id' => 'image_scale',
        'data' => [
          'height' => $settings['h'],
          'upscale' => TRUE,
          'weight' => 1,
        ],
      ]);
    }

    // Convert to WebP.
    $image_style->addImageEffect([
      'id' => 'image_convert',
      'data' => [
        'extension' => 'webp',
      ],
      'weight' => 10,
    ]);

    if ($save) {
      // Save the image style.
      $image_style->save();
    }

    return $image_style;
  }

  /**
   * Converts a settings string to an array.
   *
   * @param string $settings_string
   *   The settings string.
   *
   * @return array
   *   The settings array.
   */
  protected function parseSettings(string $settings_string): array {
    $parts = explode('_', $settings_string);

    $settings = [];

    foreach ($parts as $part) {
      $key = substr($part, -1);
      $value = substr($part, 0, -1);
      $settings[$key] = $value;
    }

    // Set width or height if aspect ratio is available.
    if (array_key_exists('r', $settings)) {
      $ratio = $settings['r'];
      $ratio_parts = explode('x', $ratio);
      // Width divided by height.
      $ratio_multiplier = $ratio_parts[0] / $ratio_parts[1];

      // Width is set but not height, calculate height.
      if (array_key_exists('w', $settings) && !array_key_exists('h', $settings)) {
        $settings['h'] = $settings['w'] / $ratio_multiplier;
      }

      // Height is set but not width, calculate width.
      if (array_key_exists('h', $settings) && !array_key_exists('w', $settings)) {
        $settings['w'] = $settings['h'] * $ratio_multiplier;
      }
    }

    // Multiply width and height if multipler is set.
    if (array_key_exists('x', $settings)) {
      $multiplier = $settings['x'];
      if (isset($settings['w'])) {
        $settings['w'] *= $multiplier;
      }
      if (isset($settings['h'])) {
        $settings['h'] *= $multiplier;
      }
    }

    // Raise number to the closest int.
    if (isset($settings['w'])) {
      $settings['w'] = ceil($settings['w']);
    }

    // Raise number to the closest int.
    if (isset($settings['h'])) {
      $settings['h'] = ceil($settings['h']);
    }

    return $settings;
  }

  /**
   * Stores a settings string as valid, so its URLs can be requested.
   *
   * Each settings string is stored as its own key value entry. That keeps
   * concurrent requests from overwriting each other's settings, and the
   * settings survive cache clears while render cached markup still points
   * at them.
   *
   * @param string $settings
   *   The settings string.
   */
  public function addValidSettings(string $settings): void {
    // Load all stored settings once, so rendering many images only writes the
    // settings that are new.
    $this->storedValidSettings ??= $this->validSettingsStore->getAll();
    if (!isset($this->storedValidSettings[$settings])) {
      $this->validSettingsStore->setIfNotExists($settings, TRUE);
      $this->storedValidSettings[$settings] = TRUE;
    }
  }

}
